title: Farhaan Pathan
logo: /assets/img/logo.png
description: Business Analyst and M.S. Supply Chain Analytics student passionate about data, technology, and process improvement. Experienced in business analysis, systems implementation, and cross-functional collaboration at Amgen and Gilead Sciences.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
